<div>
	<a href="/posts/agregar">Agregar</a>
	<table>
		<tr>
			<td>Id</td>
			<td>Titulo</td>
			<td>Fecha</td>
			<td></td>
			<td></td>
		</tr>
		<?php if(count($this->posts)) :?>
		<?php foreach( $this->posts as $post) :?>
		<tr>
			<td><?php echo $post->id;?></td>
			<td><?php echo $post->title;?></td>
			<td><?php echo $post->created_at;?></td>
			<td><a href="/posts/update/id/<?php echo $post->id;?>">Editar</a></td>
			<td><a href="/posts/delete/id/<?php echo $post->id;?>">Borrar</a></td>
			</tr>
		<?php endforeach;?>
	<?php else :?>
	<tr>
		<td colspan="3">No hay Datos</td>
	</tr>
	<?php endif;?>
	</table>
</div>